mares/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['web', 'auth'])->group(function(){
	Route::get('/', 'HomeController@dashboard')->name('home');
	Route::resource('marcas', 'MarcasController');
	Route::resource('usuarios', 'UsersController');
	Route::resource('tareas', 'TareasController');
	Route::resource('oposiciones', 'OposicionesController');
    Route::resource('transacciones', 'TransaccionesController');
    Route::get('transacciones/create/{tareaId}', 'TransaccionesController@create');
    Route::resource('estados', 'EstadosController');
    Route::get('notificacion/readAll', 'NotificationsController@readAll')->name('notifications.readAll');
});

Auth::routes();
// Route::get('/home', 'HomeController@index')->name('home');
Route::get('notificacion/{id}', 'NotificationsController@markAsRead')->name('notifications.show');

mares/resources/views/notificaciones/dashboard.blade.php
@extends('notificaciones.layout.main')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col s12">
				<em>Correo enviado el {{ date('d/m/Y') }}</em>
			</div>
		</div>
		<div class="row">
			<div class="col s12 m6">
				<div class="card-panel z-depth-2">
					<h4>Marcas negadas en los últimos {{$dias['dias_negadas']}} días</h4>
					@if(count($marcas_negadas) > 0)
					  <div class="row">
						  <div class="col s12">
							  <table class="responsive-table highlight bordered">
								<thead>
								  <th></th>
								  <th>Nombre</th>
								  <th>Estado</th>
								  <th>Última actualización</th>
								</thead>
								<tbody>
								  @foreach($marcas_negadas as $marca)
									<tr>
									  <td class="center">
										<img style="width:60px" class="circle" src="storage/marcas/{{ $marca->signo_distintivo }}">
									  </td>
									  <td>{{ $marca->nombre }}</td>
									  <td>{{ $marca->estado }}</td>
									  <td>{{ $marca->ultima_actualizacion->diffForHumans() }}</td>
									</tr>
								  @endforeach
								</tbody>
							  </table>
						  </div>
					  </div>
					@else
					  <div class="row">
						<div class="col s12">
						  <hr>
						  <strong>Sin resultados.</strong>
						</div>
					  </div>
					@endif
				</div>
			</div>
			<div class="col s12 m6">
				<div class="card-panel z-depth-2">
					<h4>Marcas con orden de publicación en los últimos {{$dias['dias_publicacion']}} días</h4>
					@if(count($marcas_publicacion) > 0)
					<div class="row">
						<div class="col s12">
							<table class="responsive-table highlight bordered">
							  <thead>
								<th></th>
								<th>Nombre</th>
								<th>Estado</th>
								<th>Última actualización</th>
							  </thead>
							  <tbody>
								@foreach($marcas_publicacion as $marca)
								  <tr>
									<td class="center">
									  <img style="width:60px" class="circle" src="storage/marcas/{{ $marca->signo_distintivo }}">
									</td>
									<td>{{ $marca->nombre }}</td>
									<td>{{ $marca->estado }}</td>
									<td>{{ $marca->ultima_actualizacion->diffForHumans() }}</td>
								  </tr>
								@endforeach
							  </tbody>
							</table>
						</div>
					</div>
					@else
					  <div class="row">
						<div class="col s12">
						  <hr>
						  <strong>Sin resultados.</strong>
						</div>
					  </div>
					@endif
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col s12 m6">
				<div class="card-panel z-depth-2">
					<h4>Marcas concedidas en los últimos {{$dias['dias_concedidas']}} días</h4>
					@if(count($marcas_concedidas) > 0)
					<div class="row">
						<div class="col s12">
							<table class="responsive-table highlight bordered">
							  <thead>
								<th></th>
								<th>Nombre</th>
								<th>Estado</th>
								<th>Última actualización</th>
							  </thead>
							  <tbody>
								@foreach($marcas_concedidas as $marca)
								  <tr>
									<td class="center">
									  <img style="width:60px" class="circle" src="storage/marcas/{{ $marca->signo_distintivo }}">
									</td>
									<td>{{ $marca->nombre }}</td>
									<td>{{ $marca->estado }}</td>
									<td>{{ $marca->ultima_actualizacion->diffForHumans() }}</td>
								  </tr>
								@endforeach
							  </tbody>
							</table>
						</div>
					</div>
					@else
					  <div class="row">
						<div class="col s12">
						  <hr>
						  <strong>Sin resultados.</strong>
						</div>
					  </div>
					@endif
				</div>
			</div>
			<div class="col s12 m6">
				<div class="card-panel z-depth-2">
					<h4>Solicitudes devueltas en los últimos {{$dias['dias_devueltas']}} días</h4>
					@if(count($marcas_devueltas) > 0)
					<div class="row">
						<div class="col s12">
							<table class="responsive-table highlight bordered">
							  <thead>
								<th></th>
								<th>Nombre</th>
								<th>Estado</th>
								<th>Última actualización</th>
							  </thead>
							  <tbody>
								@foreach($marcas_devueltas as $marca)
								  <tr>
									<td class="center">
									  <img style="width:60px" class="circle" src="storage/marcas/{{ $marca->signo_distintivo }}">
									</td>
									<td>{{ $marca->nombre }}</td>
									<td>{{ $marca->estado }}</td>
									<td>{{ $marca->ultima_actualizacion->diffForHumans() }}</td>
								  </tr>
								@endforeach
							  </tbody>
							</table>
						</div>
					</div>
					@else
					  <div class="row">
						<div class="col s12">
						  <hr>
						  <strong>Sin resultados.</strong>
						</div>
					  </div>
					@endif
				</div>
			</div>
		</div>
	</div>
@endsection

mares/resources/views/notificaciones/marcacreada.blade.php
@extends('notificaciones.layout.main')

@section('content')
	<div class="container">
		<div class="card z-depth-2">
			<div class="card-content">
				<p>{{ $fecha }}</p>
				<h5>La marca {{ $marca->nombre }} fue creada por {{ $usuario->fullName() }}</h5><br>
				<a class="btn blue waves-effect waves-light" href="{{route('marcas.show', $marca->id) }}">Ver marca</a>
			</div>
		</div>
	</div>
@endsection

mares/resources/views/notificaciones/marcaeditada.blade.php
@extends('notificaciones.layout.main')

@section('content')
	<div class="container">
		<div class="card z-depth-2">
			<div class="card-content">
				<p>{{ $fecha }}</p>
				<h5>La marca {{ $marca->nombre }} fue editada.</h5><br>
				<a class="btn blue waves-effect waves-light" href="{{ route('marcas.show', $marca->id) }}">Ver marca</a>
			</div>
		</div>
	</div>
@endsection

mares/resources/views/notificaciones/tareaasignada.blade.php
@extends('notificaciones.layout.main')

@section('content')
	<div class="container">
		<div class="card z-depth-2">
			<div class="card-content">
				<p>{{ $fecha }}</p>
				<h5>{{ $tarea->usuario->fullName() }} te ha asignado la tarea {{ $tarea->titulo }}</h5><br>
				<a class="btn blue waves-effect waves-light" href="{{route('tareas.show', $tarea->id) }}">Ver tarea</a>
			</div>
		</div>
	</div>
@endsection

mares/resources/views/notificaciones/tareaasignadarealizada.blade.php
@extends('notificaciones.layout.main')

@section('content')
	<div class="container">
		<div class="card z-depth-2">
			<div class="card-content">
				<p>{{ $fecha }}</p>
				<h5>La tarea {{ $tarea->titulo }} asignada a {{ $tarea->asignadoA->fullName() }} fue realizada</h5><br>
				<a class="btn blue waves-effect waves-light" href="{{route('tareas.show', $tarea->id) }}">Ver tarea</a>
			</div>
		</div>
	</div>
@endsection

mares/resources/views/notificaciones/transaccionrealizada.blade.php
@extends('notificaciones.layout.main')

@section('content')
	<div class="container">
		<div class="card z-depth-2">
			<div class="card-content">
				<p>{{ $fecha }}</p>
				<h5>La marca {{$marca->nombre}} cambió de estado a {{$estado->nombre}}</h5><br>
				<a class="btn blue waves-effect waves-light" href="{{route('transacciones.show', $transaccion->id) }}">Ver</a>
			</div>
		</div>
	</div>
@endsection

mares/resources/views/notificaciones/vencimientoMarcas.blade.php
@extends('notificaciones.layout.main')

@section('content')
    <div class="container">
        <div class="card z-depth-2">
            <div class="card-content">
                <p>{{ date('d-m-Y') }}</p>
                <h5>Marcas vencidas: {{ count($vencidas) }}</h5><br>
                <table class="striped">
                    <thead>
                        <th>Nombre</th>
                        <th>Fecha de vencimiento</th>
                    </thead>
                    <tbody>
                        @foreach($vencidas as $vencida)
                            <tr>
                                <td><a href="{{ route('marcas.show', $vencida->id) }}">{{ $vencida->nombre }}</a></td>
                                <td>{{ date('d-m-Y', strtotime($vencida->fecha_vencimiento)) }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <br><br>
                <h5>Marcas por vencer: {{ count($porVencer) }}</h5><br>
                <table class="striped">
                    <thead>
                        <th>Nombre</th>
                        <th>Fecha de vencimiento</th>
                    </thead>
                    <tbody>
                        @foreach($porVencer as $marca)
                            <tr>
                                <td><a href="{{ route('marcas.show', $marca->id) }}">{{ $marca->nombre }}</a></td>
                                <td>{{ date('d-m-Y', strtotime($marca->fecha_vencimiento)) }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection